version: "3.8"

services:
  api-gateway:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/app
    networks:
      - proxynet
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxynet:
    name: nginx_proxy
