version: "3.8"

services:
  api-gateway:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/app
    networks:
      - nginx_proxy
      - api_gateway_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M

networks:
  nginx_proxy:
    external: true
  api_gateway_net:
    external: true
