version: "3.8"

services:
  api-gateway:
    build: 
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    command: ./.docker/entrypoint.sh
    volumes:
      - .:/app
    networks:
      - proxynet
    
networks:
  proxynet:
    name: nginx_proxy