// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: playback.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Playback_Playback_FullMethodName = "/Playback/Playback"
)

// PlaybackClient is the client API for Playback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaybackClient interface {
	Playback(ctx context.Context, in *PlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error)
}

type playbackClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaybackClient(cc grpc.ClientConnInterface) PlaybackClient {
	return &playbackClient{cc}
}

func (c *playbackClient) Playback(ctx context.Context, in *PlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error) {
	out := new(PlaybackResponse)
	err := c.cc.Invoke(ctx, Playback_Playback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaybackServer is the server API for Playback service.
// All implementations must embed UnimplementedPlaybackServer
// for forward compatibility
type PlaybackServer interface {
	Playback(context.Context, *PlaybackRequest) (*PlaybackResponse, error)
	mustEmbedUnimplementedPlaybackServer()
}

// UnimplementedPlaybackServer must be embedded to have forward compatible implementations.
type UnimplementedPlaybackServer struct {
}

func (UnimplementedPlaybackServer) Playback(context.Context, *PlaybackRequest) (*PlaybackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Playback not implemented")
}
func (UnimplementedPlaybackServer) mustEmbedUnimplementedPlaybackServer() {}

// UnsafePlaybackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaybackServer will
// result in compilation errors.
type UnsafePlaybackServer interface {
	mustEmbedUnimplementedPlaybackServer()
}

func RegisterPlaybackServer(s grpc.ServiceRegistrar, srv PlaybackServer) {
	s.RegisterService(&Playback_ServiceDesc, srv)
}

func _Playback_Playback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaybackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackServer).Playback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Playback_Playback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackServer).Playback(ctx, req.(*PlaybackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Playback_ServiceDesc is the grpc.ServiceDesc for Playback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Playback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Playback",
	HandlerType: (*PlaybackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Playback",
			Handler:    _Playback_Playback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playback.proto",
}
