import { PlaybackProvider } from '@/contexts/PlaybackContext'
import '@/styles/globals.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <PlaybackProvider>
          {children}
        </PlaybackProvider>
      </body>
    </html>
  )
}
