version: "3.8"

services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - .:/app
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 800M
