version: "3.8"

services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./http.d:/etc/nginx/http.d:ro
    ports:
      - 8080:80
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true