version: "3.8"

services:
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./http.d:/etc/nginx/http.d:ro
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - 8080:80